apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n5eu96q6g-go
  janus-idp.io/tekton: n5eu96q6g-go
  backstage.io/kubernetes-id: n5eu96q6g-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n5eu96q6g-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
