apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: n5eu96q6g-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: n5eu96q6g-go 
  name: n5eu96q6g-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: n5eu96q6g-go 
